### ISSUE TITLE
Suggestions list shouldn't close as long as the focus stays in the container

### ISSUE THREAD

**Issue by mh-nichts** [mynamesleon/aria-autocomplete#11]
This is also a point notified by our accessibility expert : while navigating with the keyboard, we want the suggestions list to stay open as long as we're still in the container.

There are special conditions to handle this in the `handleComponentBlur()` function, but it seems that it's not working : when focus goes from input to "show all" or a selected item, the suggestions list closes (this can be tested in example 2).

It seems that it's because the 'isSelectedItem()' function returns `undefined` instead of `false`, hence the condition isn't correctly interpreted.

**Comment by mh-nichts** [comment]
OK, I misunderstood the condition in `handleComponentBlur()` : it's explicitly set to close the suggestions list when focus goes to "show all" or a selected item.

Still it would be interesting to fix `isSelectedItem()` so it returns only `true` or `false`, because it should return a boolean.

Back to the closing of suggestions list : the accessibility issue here is for mobile/tactile devices, where explore by touch isn't very practical especially on small screens. In those cases, it's better to be able to navigate by swipe in the list. To do this, the list must either stay open until we "arrive" on it (after "show all" and selected items), or the list should be just after the text input in the HTML order.

My suggestion to handle this while keeping the original condition : move the list HTML before the selected items (instead of after). It would also be more consistent with the visual aspect, especially without autogrow : the selected items are after the input/"show all"/list.
If the "show all" button is present, the list must stay after it, to keep consistency with the disclosure pattern : if we keep closing the list on this button, there will still be a problem on mobile/tactile navigation, and then the only solution I see is not setting the `showAllControl` option.

**Comment by mynamesleon** [comment]
Thank you for pointing this one out. I've also wondered about eventually adding an option to control where the selected items render in the DOM - before or after the input - particularly as the `autoGrow` mode is styled by default to look like they're before the input and the tabbing order doesn't match that. I'll have to explore that further at a later point.

**Comment by mh-nichts** [comment]
Thanks for the change !
