### ISSUE TITLE
Differentiate controls of several autocomplete on the same page

### ISSUE THREAD

**Issue by mh-nichts** [mynamesleon/aria-autocomplete#14]
When there are several autocompletes on the same page, some controls have the same text : "show all" and "delete all" controls, selected options. 
This makes them hard to distinguish while navigating with a screen reader.
To differentiate them, the suggestion of our accessibility expert is to add a aria-describedby attribute pointing to the label of the corresponding autocomplete. The label text would then supplement the control text to make it more explicit.

**Comment by mynamesleon** [comment]
I'll admit, I was mostly relying on the `aria-owns` attribute on the main input to cover this, so that the relationship would be clear from the page (and screen reader) hierarchy. That is more of an implied relationship though, as that won't be made clear by all screen readers, so this is definitely a worthwhile enhancement.

**Comment by mh-nichts** [comment]
Thanks for the change !
Indeed when there is a relevant legend, that relationship isn't necessary, and when there is no label... well we can't do much, except handling the condition as you & we did.
But I hadn't thought about the scenario of wrapping the whole control in a label : doesn't this cause other problems anyway ? (for example, having a ul/li inside a label isn't valid HTML)

**Comment by mynamesleon** [comment]
Yes wrapping the whole control in a `<label>` would cause problems, and invalid HTML as block elements would be generated inside it. However, although that's invalid, the plugin doesn't actively prevent someone from doing that. So I wouldn't be at all surprised if someone eventually did that!
