### ISSUE TITLE
Handling required attribute / error message

### ISSUE THREAD

**Issue by mh-nichts** [mynamesleon/aria-autocomplete#39]
Hello,

Thanks again for your plug-in, which we use on several projects.

We realized recently that if we use it on required fields (`<select required>`), it seems not to work correctly : 

- no required attribute on the generated input, so no screen-reader announcement that the field is indeed required
- when trying to submit the form without filling that field, the browser wants to display the native HTML5 error message on the required select, but as it's invisible (with display none), it's not possible : so the form isn't submitted but there is no clue for the user to know what's wrong

Am I missing something in the process, is there a way to handle correctly that kind of required fields ?

**Comment by mynamesleon** [comment]
Hi @mh-nichts 

The plugin intentionally doesn't try to infer any validation rules from the existing element(s) when you use it to progressively enhance them - it would be feasible to move things like the `required` attribute along, but it would be impossible to automatically copy any custom JS rules across. That's why so many callback methods are available - so that you can handle any validation needs yourself.

**Comment by mh-nichts** [comment]
Here is the code I used, if it can help anyone :
```
onReady: (componentWrapper) => {
  const autocompleteInput = componentWrapper.querySelector(
    '.aria-autocomplete__input',
  );

  // avoid native validation on hidden select (see issue : https://github.com/mynamesleon/aria-autocomplete/issues/39 )
  autocomplete.removeAttribute('required');

  // init custom validation on autocomplete field, and update at each value change
  checkAutocompleteFilled(autocomplete, autocompleteInput);

  autocomplete.addEventListener('change', (event) => {
    checkAutocompleteFilled(autocomplete, autocompleteInput);
  });
},
```
and 
```
function checkAutocompleteFilled(select, autocompleteInput) {
  let validity = '';
  if (select.value === '') {
    validity = 'Please fill in this field.';
  }

  autocompleteInput.setCustomValidity(validity);
}
```
